### PR TITLE
Create Landing Page for Git, GitHub, and Open Source Overview

### PR DESCRIPTION
**Pull request by smonishkumar**
This pull request introduces a new landing page containing basic overview of git, github and open source created using HTML and CSS. The changes include:

Created a clean and semantic HTML layout.
Designed the page with modern CSS, using Flexbox for layout.
Developed a responsive layout that adapts to various screen sizes using CSS media queries.
Added information regarding git, github and opensource which will help beginners.

Related issues: 
Closes issue #4 

This is my first open source contribution. Any feedback and suggestions will be helpful.😃

### CODE REVIEW

**Comment by Prithwi32** [comment]
@smonishkumar great contribution..Please could u add screen-shot for a quick review

**Comment by smonishkumar** [comment]
Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_4
Screenshot_5
Screenshot_6
Screenshot_7

The buttons at the top directly scrolls to the respective section on clicking.

**Comment by Prithwi32** [comment]
> Screenshot_1 Screenshot_2 Screenshot_3 Screenshot_4 Screenshot_5 Screenshot_6 Screenshot_7
> 
> The buttons at the top directly scrolls to the respective section on clicking.

@smonishkumar Nice   .. . styling can be improved...Still good contribution... Congratulations 🎉👏

**Review by Prithwi32 — APPROVED** [review]
Good work...

**Comment by smonishkumar** [comment]
> > Screenshot_1 Screenshot_2 Screenshot_3 Screenshot_4 Screenshot_5 Screenshot_6 Screenshot_7
> > The buttons at the top directly scrolls to the respective section on clicking.
> 
> @smonishkumar Nice .. . styling can be improved...Still good contribution... Congratulations 🎉👏

Thank you for your feedback...any suggestions on how to improve styling?

**Comment by Prithwi32** [comment]
> > > Screenshot_1 Screenshot_2 Screenshot_3 Screenshot_4 Screenshot_5 Screenshot_6 Screenshot_7
> > > The buttons at the top directly scrolls to the respective section on clicking.
> > 
> > 
> > @smonishkumar Nice .. . styling can be improved...Still good contribution... Congratulations 🎉👏
> 
> Thank you for your feedback...any suggestions on how to improve styling?

Adding some related images...copy option for commands, using some color palette for website

**Comment by smonishkumar** [comment]
> > > > Screenshot_1 Screenshot_2 Screenshot_3 Screenshot_4 Screenshot_5 Screenshot_6 Screenshot_7
> > > > The buttons at the top directly scrolls to the respective section on clicking.
> > > 
> > > 
> > > @smonishkumar Nice .. . styling can be improved...Still good contribution... Congratulations 🎉👏
> > 
> > 
> > Thank you for your feedback...any suggestions on how to improve styling?
> 
> Adding some related images...copy option for commands, using some color palette for website

Noted👍

**Pull request merged**
